[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
local = "http://127.0.0.1:8545"
kite_test = "https://rpc-testnet.gokite.ai"
base = "https://mainnet.base.org"